services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

  cassandra:
    image: cassandra:latest
    container_name: cassandra_container
    ports:
      - "9042:9042"
    networks:
      - backend
    environment:
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra_data:/var/lib/cassandra

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
  mongo_data:
  cassandra_data:
